# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/react-client"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
        - "*eslint*|eslint|eslint*"
      mantine:
        patterns:
        - "@mantine*"
      react:
        patterns:
        - "react|react-dom"
      types:
        patterns:
        - "@types/"
      typescript-eslint:
        patterns:
        - "@typescript-eslint*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      jupnp:
        patterns:
        - "org.jupnp:org.jupnp"
      logback:
        patterns:
        - "ch.qos.logback"
      mockito:
        patterns:
        - "mockito"
      twelvemonkeys:
        patterns:
        - "com.twelvemonkeys.imageio"
