package net.pms.store.item;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import java.io.File;
import java.sql.DriverManager;
import net.pms.PMS;
import net.pms.configuration.UmsConfiguration;
import net.pms.database.MediaTableStoreIds;
import net.pms.store.ResumeObj;
import net.pms.store.StoreContainer;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class RealFileResumeIdentityTest {
	private static net.pms.renderers.Renderer renderer;

	@BeforeAll
	static void configure() throws Exception {
		System.setProperty(PMS.PROPERTY_RUNNING_TESTS, "true");
		PMS.setConfiguration(new UmsConfiguration(false));
		renderer = new net.pms.renderers.Renderer((String) null);
	}

	@Test
	void resumeCopyHasItsOwnPersistentId() throws Exception {
		try (var db = DriverManager.getConnection("jdbc:h2:mem:")) {
			try (var stmt = db.createStatement()) {
				stmt.execute(
						"CREATE TABLE STORE_IDS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
								" PARENT_ID BIGINT, NAME VARCHAR, OBJECT_TYPE VARCHAR, UPDATE_ID BIGINT)");
			}
			var parent = new StoreContainer(renderer, "folder", null);
			parent.setId("7");

			var original = new RealFile(renderer, new File("avatar.mkv"));
			original.setParent(parent);
			var resume = original.clone();
			resume.setResume(new ResumeObj(new File("avatar.mkv_hash_1.resume")));
			resume.setParent(parent);
			assertTrue(resume.isResume());

			long originalId = MediaTableStoreIds.getResourceMediaStoreId(db, original).getId();
			long resumeId = MediaTableStoreIds.getResourceMediaStoreId(db, resume).getId();
			assertNotEquals(originalId, resumeId);

			// Same ids on the next lookup, e.g. after a restart
			assertEquals(originalId, MediaTableStoreIds.getResourceMediaStoreId(db, original).getId());
			assertEquals(resumeId, MediaTableStoreIds.getResourceMediaStoreId(db, resume).getId());
		}
	}
}
