package net.pms.store.item;

import static org.junit.jupiter.api.Assertions.*;

import java.io.File;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.HashSet;
import net.pms.PMS;
import net.pms.configuration.UmsConfiguration;
import net.pms.database.MediaTableStoreIds;
import net.pms.media.subtitle.MediaSubtitle;
import net.pms.store.container.ChapterFileTranscodeVirtualFolder;
import net.pms.store.container.FileTranscodeVirtualFolder;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class RealFileExternalSubtitleIdentityTest {
	private static net.pms.renderers.Renderer renderer;

	@BeforeAll
	static void configure() throws Exception {
		System.setProperty(PMS.PROPERTY_RUNNING_TESTS, "true");
		PMS.setConfiguration(new UmsConfiguration(false));
		renderer = new net.pms.renderers.Renderer((String) null);
	}

	private RealFile item(String subtitlePath, int id) {
		var item = new RealFile(renderer, new File("avatar.mkv"));
		var sub = new MediaSubtitle();
		sub.setId(id);
		if (subtitlePath != null) {
			sub.setExternalFileOnly(new File(subtitlePath));
		}
		item.setMediaSubtitle(sub);
		return item;
	}

	@Test
	void externalChoicesHaveDistinctPersistentIdsAndSurviveReordering() throws Exception {
		try (var db = DriverManager.getConnection("jdbc:h2:mem:")) {
			try (var stmt = db.createStatement()) {
				stmt.execute(
						"CREATE TABLE STORE_IDS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
								" PARENT_ID BIGINT, NAME VARCHAR, OBJECT_TYPE VARCHAR, UPDATE_ID BIGINT)");
			}
			var parent = new FileTranscodeVirtualFolder(null, item(null, 0));
			parent.setId("7");
			var ids = new HashMap<String, Long>();
			for (String file :
					new String[] {
						"avatar.cze.vtt", "avatar.rum.srt", "avatar.swe.srt", "subs/avatar.swe.srt"
					}) {
				var choice = item(file, 0);
				choice.setParent(parent);
				var stored = MediaTableStoreIds.getResourceMediaStoreId(db, choice);
				assertNotNull(stored);
				ids.put(file, stored.getId());
			}
			assertEquals(4, new HashSet<>(ids.values()).size());
			for (var entry : ids.entrySet()) {
				// A rescan can change the numeric track id, but must keep the file's persistent identity.
				var choice = item(entry.getKey(), 123);
				choice.setParent(parent);
				assertEquals(
						entry.getValue().longValue(),
						MediaTableStoreIds.getResourceMediaStoreId(db, choice).getId());
			}
			var embedded = item(null, 0);
			embedded.setParent(parent);
			assertFalse(
					ids.containsValue(MediaTableStoreIds.getResourceMediaStoreId(db, embedded).getId()));
		}
	}

	@Test
	void chaptersAlsoDistinguishExternalFiles() {
		var first = item("avatar.rum.srt", 0);
		var second = item("avatar.swe.srt", 0);
		var parent = new ChapterFileTranscodeVirtualFolder(null, "chapters", first, 5);
		first.setParent(parent);
		second.setParent(parent);
		assertNotEquals(first.getSystemName(), second.getSystemName());
	}

	@Test
	void ordinaryFileIdentityDoesNotDependOnSelectedSubtitles() {
		assertEquals(
				item("avatar.cze.vtt", 0).getSystemName(), item("avatar.swe.srt", 0).getSystemName());
	}
}
