version = 1

exclude_patterns = ["src/main/external-resources/web/util/**"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "8"

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["angularjs"]