FROM ubuntu:22.04

LABEL org.opencontainers.image.title="Universal Media Server"

RUN apt-get update
RUN apt-get install coreutils ffmpeg mediainfo openjdk17-jre iputils-ping mplayer fonts-dejavu-web fonts-dejavu -y

WORKDIR /profile

COPY ./profile /profile

COPY ./app/UMS.conf /profile

WORKDIR /ums

COPY ./app /ums

VOLUME /media

VOLUME /profile

EXPOSE 1900/udp 5001/tcp 5353/udp 9001/tcp 9002/tcp

ENV UMS_PROFILE=/profile

ENV JDK_JAVA_OPTIONS="-Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djna.nosys=true"

ENTRYPOINT [ "java", "-jar", "ums.jar" ]
