#!/bin/sh

# Launch UMS. To expose parameters, use the syntax: ${VARNAME-default_value}
exec java \
  "${JVM_OPTS--Xmx512M}" -XX:+UnlockExperimentalVMOptions \
  -Dfile.encoding="${JVM_ENCODING-UTF-8}" \
  -Djava.net.preferIPv4Stack="${JVM_PREFERIPV4-true}" \
  -Djna.nosys="${JVM_JNA_NOSYS-true}" \
  -DUMS_PROFILE="${UMS_PROFILE-/profile}" \
  -cp ums.jar net.pms.PMS "${*}"
