var VK_ENTER					=  13;//OK
var VK_MENU_2					=  18;//MENU(SAMSUNG)
var VK_PAUSE					=  19;//PAUSE(SAMSUNG)
var VK_RETURN					=  27;//RETURN / RELOAD
var VK_PAGE_UP					=  33;//PAGE UP
var VK_PAGE_DOWN				=  34;//PAGE DOWN
var VK_LEFT						=  37;
var VK_UP						=  38;
var VK_RIGHT					=  39;
var VK_DOWN						=  40;
var VK_DASH						=  47;//DASH ( - ) o SLASH ( / )
var VK_0						=  48;
var VK_1						=  49;
var VK_2						=  50;
var VK_3						=  51;
var VK_4						=  52;
var VK_5						=  53;
var VK_6						=  54;
var VK_7						=  55;
var VK_8						=  56;
var VK_9						=  57;
var VK_REWIND					= 177;//<<
var VK_STOP						= 178;//STOP
var VK_PLAY						= 179;//>|
var VK_FAST_FWD					= 176;//>>
var VK_MINUS					= 189;//MINUS( - )(SAMSUNG)
var VK_RED						= 403;//RED
var VK_GREEN					= 404;//GREEN
var VK_YELLOW					= 405;//YELLOW
var VK_BLUE						= 406;//BLUE
var VK_REWIND_2					= 412;//<<(SAMSUNG)
var VK_STOP_2					= 413;//STOP(SAMSUNG)
var VK_PLAY_2					= 415;//>(SAMSUNG)
var VK_RECORD					= 416;//o(SAMSUNG)
var VK_FAST_FWD_2				= 417;//>>(SAMSUNG)
var VK_CHANNEL_UP				= 427;//CH+
var VK_CHANNEL_DOWN				= 428;//CH-
var VK_VOLUME_UP				= 447;//VOL+(SAMSUNG)
var VK_VOLUME_DOWN				= 448;//VOL-(SAMSUNG)
var VK_VOLUME_MUTE				= 449;//MUTE(SAMSUNG)
var VK_INFO						= 457;//DISPLAY / INFO
var VK_GUIDE					= 458;//GUIDE(SAMSUNG)
var VK_BACK_2					= 461;//BACK(UNK)
var VK_MENU						= 462;//MENU(SEIKI)
var VK_CHANNEL_LIST				= 475;//CH.LIST
var VK_ASPECT   				= 483;//ASPECT
var VK_SOURCE   				= 529;//SOURCE
var VK_CLOSEDCAPTION			= 530;//CC
var VK_MTS         				= 536;//MTS
var VK_BACK						= 10009;//BACK(SAMSUNG)
var VK_SOURCE					= 10072;//SOURCE(SAMSUNG)
var VK_CHANNEL_LIST_2			= 10073;//CH.LIST(SAMSUNG)
var VK_TOOLS					= 10135;//TOOLS(SAMSUNG)
var VK_PICTURE_SIZE				= 10140;//PICTURE SIZE
var VK_EMANUAL					= 10146;//E-MANUAL
var VK_EXIT						= 10182;//EXIT(SAMSUNG)
var VK_PREVIOUS_CHANNEL			= 10190;//<>CH(SAMSUNG)
var VK_MTS_2       				= 10195;//MTS(SAMSUNG)
var VK_3D						= 10199;//3D(SAMSUNG)
var VK_TELETEXT					= 10200;//TELETEXT(SAMSUNG)
var VK_CLOSEDCAPTION_2			= 10221;//CC(SAMSUNG)
var VK_SEARCH					= 10225;//SEARCH(SAMSUNG)
var VK_SOCCER					= 10228;//SOCCER(SAMSUNG)
var VK_TRACK_PREVIOUS			= 10232;//|<TRACK_PREVIOUS(SAMSUNG)
var VK_TRACK_NEXT				= 10233;//>|TRACK_NEXT(SAMSUNG)
var VK_PLAY_PAUSE				= 10252;//PLAY&PAUSE (SAMSUNG)
var VK_EXTRA					= 10253;//EXTRA(SAMSUNG)