package net.pms.database;

import static org.junit.jupiter.api.Assertions.*;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.concurrent.atomic.AtomicInteger;
import net.pms.PMS;
import net.pms.configuration.UmsConfiguration;
import net.pms.store.MediaStoreId;
import net.pms.store.StoreContainer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

public class MediaTableStoreIdsTest {
	@BeforeAll
	public static void configure() throws Exception {
		System.setProperty(PMS.PROPERTY_RUNNING_TESTS, "true");
		PMS.setConfiguration(new UmsConfiguration(false));
	}

	@Test
	public void existingResourceUsesOneQueryAndPreservesAllFields() throws Exception {
		try (Connection db = database()) {
			db.createStatement().executeUpdate("INSERT INTO STORE_IDS VALUES (42, 7, 'movie', 'RealFile', 91)");
			AtomicInteger queries = new AtomicInteger();
			Connection counted = (Connection) Proxy.newProxyInstance(Connection.class.getClassLoader(),
				new Class<?>[] {Connection.class}, (proxy, method, args) -> {
					if (method.getName().equals("prepareStatement")) {
						queries.incrementAndGet();
					}
					try {
						return method.invoke(db, args);
					} catch (InvocationTargetException e) {
						throw e.getCause();
					}
				});
			MediaStoreId found = MediaTableStoreIds.getResourceMediaStoreId(counted, resource(7, "movie"));
			assertNotNull(found);
			assertEquals(1, queries.get(), "Existing row must not be read twice");
			assertEquals(42, found.getId());
			assertEquals(7, found.getParentId());
			assertEquals("movie", found.getName());
			assertEquals("RealFile", found.getObjectType());
			assertEquals(91, found.getUpdateId());
			assertEquals(91, MediaTableStoreIds.getMediaStoreId(db, 42).getUpdateId());
		}
	}

	@Test
	public void missingResourceIsInsertedAndReusedWithinItsParent() throws Exception {
		try (Connection db = database()) {
			StoreContainer resource = resource(7, "new movie");
			MediaStoreId first = MediaTableStoreIds.getResourceMediaStoreId(db, resource);
			assertNotNull(first);
			assertEquals("new movie", first.getName());
			assertEquals("StoreContainer", first.getObjectType());
			assertEquals(7, first.getParentId());
			assertEquals(0, first.getUpdateId());
			assertEquals(first.getId(), MediaTableStoreIds.getResourceMediaStoreId(db, resource).getId());
			assertNotEquals(first.getId(), MediaTableStoreIds.getResourceMediaStoreId(db, resource(8, "new movie")).getId());
			assertNull(MediaTableStoreIds.getMediaStoreId(db, -999));
		}
	}

	@Test
	public void invalidInputsReturnNull() throws Exception {
		try (Connection db = database()) {
			assertNull(MediaTableStoreIds.getResourceMediaStoreId(null, resource(7, "movie")));
			assertNull(MediaTableStoreIds.getResourceMediaStoreId(db, null));
			assertNull(MediaTableStoreIds.getResourceMediaStoreId(db, new StoreContainer(null, "orphan", null)));
		}
	}

	private static StoreContainer resource(long parentId, String name) {
		StoreContainer parent = new StoreContainer(null, "parent", null);
		parent.setId(Long.toString(parentId));
		StoreContainer child = new StoreContainer(null, name, null);
		child.setParent(parent);
		return child;
	}

	private static Connection database() throws Exception {
		Connection db = DriverManager.getConnection("jdbc:h2:mem:");
		try (var stmt = db.createStatement()) {
			stmt.execute("CREATE TABLE STORE_IDS (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, PARENT_ID BIGINT, NAME VARCHAR, OBJECT_TYPE VARCHAR, UPDATE_ID BIGINT)");
		}
		return db;
	}
}
