name: Build releases

# this chunk is for testing, should be reverted before merge
on: [push, pull_request]
# on:
#   push:
#     tags:
#       - '*'

jobs:
  # appimage:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Set up JDK
  #       uses: actions/setup-java@v5
  #       with:
  #         distribution: 'liberica'
  #         java-version: 17
  #     - name: Install MediaInfo
  #       run: |
  #         sudo apt-get -y install libmms0
  #         wget --no-check-certificate https://mediaarea.net/download/binary/libmediainfo0/25.10/libmediainfo0v5_25.10-1_amd64.Ubuntu_24.04.deb
  #         sudo dpkg -i libmediainfo0v5_25.10-1_amd64.Ubuntu_24.04.deb
  #     - name: Build x86_64 release
  #       run: mvn package -P linux-x86_64 -DskipTests
  #     - name: Install AppImage dependencies
  #       uses: awalsh128/cache-apt-pkgs-action@v1.6.0
  #       with:
  #         packages: desktop-file-utils
  #     - name: Build AppImage
  #       run: |
  #         bash ./.github/workflows/build-appimage.sh
  #         mkdir dist
  #         mv ./target/*AppImage* dist/
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v7
  #       with:
  #         name: AppImage
  #         path: 'dist'
  macos-arm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - name: Set up JRE
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
          java-package: jre
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Extract tag
        # Uncomment below before merging
        # run: echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
        run: echo "TAG=15.5.0-SNAPSHOT" >> $GITHUB_ENV
      - name: Save JRE version in path format
        id: paths
        run: cd /Users/runner/hostedtoolcache/Java_Liberica_jre/ && ls && echo "jrePath=$(ls)" >> "$GITHUB_OUTPUT"
      - name: Logging
        run: cd /Users/runner/hostedtoolcache/Java_Liberica_jre/${{ steps.paths.outputs.jrePath }}/arm64 && ls
      - name: Write specific Java version to Maven pom config
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: '**/pom.xml'
          search-text: 'JAVA_PATH_VERSION'
          replacement-text: ${{ steps.paths.outputs.jrePath }}
      - name: Build package
        run: mvn -P macos-arm-ci package -DskipTests=true
      - name: Write tag to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './.github/workflows/dependencies/gon-config-*.json'
          search-text: 'VERSION_TAG'
          replacement-text: ${{ env.TAG }}
      - name: Write password to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './.github/workflows/dependencies/gon-config-*.json'
          search-text: 'APPLE_PASSWORD'
          replacement-text: ${{secrets.APPLE_PASSWORD}}
      - name: Import codesign cert
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - name: Run pre-build signing step
        run: ./.github/workflows/dependencies/gon ./.github/workflows/dependencies/gon-config-prebuild.json
      - name: Logging
        run: cd ./target/ums-15.5.0-SNAPSHOT-distribution/ && ls
      - name: Run post-build signing step
        run: ./.github/workflows/dependencies/gon ./.github/workflows/dependencies/gon-config-build-arm.json
      - name: Move file to dist folder
        run: |
          mkdir dist
          mv ./.github/workflows/dependencies/UMS-macOS-${{ env.TAG }}-arm.dmg dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: AppImage
          path: **/*.dmg
  macos-intel:
    runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v6
      - name: Set up JRE
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
          java-package: jre
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Extract tag
        # Uncomment below before merging
        # run: echo "TAG=$GITHUB_REF_NAME" >> $GITHUB_ENV
        run: echo "TAG=15.5.0-SNAPSHOT" >> $GITHUB_ENV
      - name: Save JRE version in path format
        id: paths
        run: cd /Users/runner/hostedtoolcache/Java_Liberica_jre/ && ls && echo "jrePath=$(ls)" >> "$GITHUB_OUTPUT"
      - name: Logging
        run: cd /Users/runner/hostedtoolcache/Java_Liberica_jre/${{ steps.paths.outputs.jrePath }}/arm64 && ls
      - name: Write specific Java version to Maven pom config
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: '**/pom.xml'
          search-text: 'JAVA_PATH_VERSION'
          replacement-text: ${{ steps.paths.outputs.jrePath }}
      - name: Build package
        run: mvn -P macos-ci package -DskipTests=true
      - name: Write tag to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './.github/workflows/dependencies/gon-config-*.json'
          search-text: 'VERSION_TAG'
          replacement-text: ${{ env.TAG }}
      - name: Write password to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './.github/workflows/dependencies/gon-config-*.json'
          search-text: 'APPLE_PASSWORD'
          replacement-text: ${{secrets.APPLE_PASSWORD}}
      - name: Import codesign cert
        uses: apple-actions/import-codesign-certs@v3
        with: 
          p12-file-base64: ${{ secrets.APPSTORE_CERTIFICATES_FILE_BASE64 }}
          p12-password: ${{ secrets.APPSTORE_CERTIFICATES_PASSWORD }}
      - name: Run pre-build signing step
        run: ./.github/workflows/dependencies/gon ./.github/workflows/dependencies/gon-config-prebuild.json
      - name: Logging
        run: cd ./target/ums-15.5.0-SNAPSHOT-distribution/ && ls
      - name: Run post-build signing step
        run: ./.github/workflows/dependencies/gon ./.github/workflows/dependencies/gon-config-build-arm.json
      - name: Move file to dist folder
        run: |
          mkdir dist
          mv ./.github/workflows/dependencies/UMS-macOS-${{ env.TAG }}-x86_64.dmg dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: AppImage
          path: **/*.dmg


