name: Build releases

# this chunk is for testing, should be reverted before merge
on: [push, pull_request]
# on:
#   push:
#     tags:
#       - '*'

jobs:
  appimage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Install MediaInfo
        run: |
          sudo apt-get -y install libmms0
          wget --no-check-certificate https://mediaarea.net/download/binary/libmediainfo0/25.10/libmediainfo0v5_25.10-1_amd64.Ubuntu_24.04.deb
          sudo dpkg -i libmediainfo0v5_25.10-1_amd64.Ubuntu_24.04.deb
      - name: Build x86_64 release
        run: mvn package -P linux-x86_64 -DskipTests
      - name: Install AppImage dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: desktop-file-utils
      - name: Build AppImage
        run: |
          bash ./.github/workflows/build-appimage.sh
          mkdir dist
          mv ./target/*AppImage* dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: AppImage
          path: 'dist'
  macos-arm:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v6
      - name: Set up JRE
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
          java-package: jre
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: 17
      - name: Build package
        run: mvn -P macos-arm-ci package -DskipTests=true
      - name: Write tag to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './dependencies/gon-config-*.json'
          search-text: 'VERSION_TAG'
          replacement-text: $GITHUB_REF_NAME
      - name: Write username to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './dependencies/gon-config-*.json'
          search-text: 'APPLE_USERNAME'
          replacement-text: ${{secrets.APPLE_USERNAME}}
      - name: Write password to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './dependencies/gon-config-*.json'
          search-text: 'APPLE_PASSWORD'
          replacement-text: ${{secrets.APPLE_PASSWORD}}
      - name: Write provider to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './dependencies/gon-config-*.json'
          search-text: 'APPLE_PROVIDER'
          replacement-text: ${{secrets.APPLE_PROVIDER}}
      - name: Write application identity to Gon configs
        uses: richardrigutins/replace-in-files@v3.0.0
        with:
          files: './dependencies/gon-config-*.json'
          search-text: 'APPLICATION_IDENTITY'
          replacement-text: ${{secrets.APPLICATION_IDENTITY}}
      - name: Run pre-build signing step
        run: ./dependencies/gon ./gon-config-prebuild.json
      - name: Run post-build signing step
        run: ./dependencies/gon ./gon-config-build-arm.json
      - name: Build AppImage
        run: |
          mkdir dist
          mv ./.github/workflows/dependencies/UMS-macOS-$GITHUB_REF_NAME-arm.dmg dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: AppImage
          path: 'dist'

