name: Label conflicted PRs

on:
  # So that PRs touching the same files as the push are updated
  push:
  # So that the `dirtyLabel` is removed if conflicts are resolve
  # We recommend `pull_request_target` so that github secrets are available.
  # In `pull_request` we wouldn't be able to change labels of fork PRs
  pull_request_target:
    types: [synchronize]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: check if prs are dirty
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      uses: eps1lon/actions-label-merge-conflict@v3
      id: check
      with:
        dirtyLabel: "conflicting"
        repoToken: "${{ secrets.AUTOMATION_TOKEN }}"
        commentOnDirty: '@dependabot recreate'
